### Users

GET http://localhost:3000/users

###

GET http://localhost:3000/users/4

###

POST http://localhost:3000/users
content-type: application/json

{
    "email": "guilherme@email.com",
    "password": "2910str1"
}

###

PUT http://localhost:3000/users/3
content-type: application/json

{
    "email": "matheus@email.com.br",
    "password": "04892wwm"
}

### 

DELETE http://localhost:3000/users/3

### Auth

POST http://localhost:3000/authentication
content-type: application/json

{
    "email": "guilherme@email.com",
    "password": "2910str1"
}

### Urls

POST http://localhost:3000/urls
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiZ3VpbGhlcm1lQGVtYWlsLmNvbSIsInVzZXJJZCI6NCwiaWF0IjoxNzMzNjk5MzYwLCJleHAiOjE3MzM3MzUzNjB9.OLxwuDexnHjBgvz9VS9TLe3dTJfmiUX87CYryzjj-xc

{
    "originalUrl": "https://medium.com/@kupriyanov.vo/setup-hono-drizzle-orm-template-project-for-cloudflare-d1-and-r2-bucket-9e13cdd37156"
}

###

GET http://localhost:3000/urls
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidGVzdGVAZW1haWwuY29tIiwidXNlcklkIjo1LCJpYXQiOjE3MzQwOTE0NzYsImV4cCI6MTczNDEyNzQ3Nn0.q_3nbjCbXPXa127cRlnp6KDkiIBO7cxhUfEM035XKTQ

### 

PATCH http://localhost:3000/urls/23
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiZ3VpbGhlcm1lQGVtYWlsLmNvbSIsInVzZXJJZCI6NCwiaWF0IjoxNzMzNjk5MzYwLCJleHAiOjE3MzM3MzUzNjB9.OLxwuDexnHjBgvz9VS9TLe3dTJfmiUX87CYryzjj-xc

{
    "originalUrl": "https://medium.com/@harendra21/how-i-am-using-a-lifetime-100-free-server-bd241e3a347a"
}

###

DELETE http://localhost:3000/urls/22
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiZ3VpbGhlcm1lQGVtYWlsLmNvbSIsInVzZXJJZCI6NCwiaWF0IjoxNzMzNjk5MzYwLCJleHAiOjE3MzM3MzUzNjB9.OLxwuDexnHjBgvz9VS9TLe3dTJfmiUX87CYryzjj-xc

###

GET http://localhost:3000/fx9hQw